services:

  postgres:
    image: postgres:16-alpine
    container_name: bip-postgres
    environment:
      POSTGRES_DB: bipdb
      POSTGRES_USER: bip
      POSTGRES_PASSWORD: bip123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bip -d bipdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - bip-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: bip-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HEALTH_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: auth.victor-dev.tech
    command: start-dev --import-realm --health-enabled=true
    ports:
      - "127.0.0.1:8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 2>/dev/null && echo -e 'GET /health/ready HTTP/1.0\r\n\r\n' >&3 && grep -q 'UP' <&3"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 90s
    restart: unless-stopped
    networks:
      - bip-net

  backend:
    image: victormachado38/bip-backend:prod
    container_name: bip-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bipdb
      SPRING_DATASOURCE_USERNAME: bip
      SPRING_DATASOURCE_PASSWORD: bip123
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/bip-realm/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.victor-dev.tech/realms/bip-realm
      APP_CORS_ALLOWED_ORIGIN: https://app.victor-dev.tech
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    restart: on-failure:5
    networks:
      - bip-net

  frontend:
    image: victormachado38/bip-frontend:prod
    container_name: bip-frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bip-net

volumes:
  postgres_data:

networks:
  bip-net:
    driver: bridge
